---
deployment:
  tasks:
    - export DEPLOYPATH=/home/brijpets/public_html/face-recognition-website/
    - /bin/cp -r /home/brijpets/repositories/face-recognition-website/face-recognition-brain/build/* $DEPLOYPATH